### ISSUE TITLE
Error: Cannot find module 'debug'

### ISSUE THREAD

**Issue by qrkourier** [alessioalex/git-authors#2]
```bash
git-authors git/master 
❯ REPO=~/Sites/shiny-project node ./example.js 
module.js:549
    throw err;
    ^

Error: Cannot find module 'debug'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/kbingham/Sites/git-authors/index.js:3:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**Comment by qrkourier** [comment]
The solution was to first do `npm install` in the working copy.
