### ISSUE TITLE
ambiguous argument 'master': unknown revision or path not in the working tree

### ISSUE THREAD

**Issue by qrkourier** [alessioalex/git-authors#3]
```bash
git-authors git/master 
❯ REPO=~/Sites/shiny-project node ./example.js
/home/kbingham/Sites/git-authors/example.js:8
  if (err) { throw err; }
             ^

Error: Command failed: git --git-dir=/home/kbingham/Sites/shiny-project shortlog -sne master < /dev/tty || git --git-dir=/home/kbingham/Sites/shiny-project shortlog -sne master
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:567:12)
```

**Comment by qrkourier** [comment]
The solution was to include the `.git` part of the path to the repo to query because it is required by the `--work-dir` param to Git CLI.

```bash
❯ REPO=~/Sites/shiny-project/.git node ./example.js
```
